### ISSUE TITLE
to high argument

### ISSUE THREAD

**Issue by the-jomper** [christheboss894/Mods#2]
Hi it seems you have a mestek right here in the 400 argument https://github.com/christheboss894/Mods/blob/ef3daf52193783d56c23bae91a9ea31b875b7079/VolcanoidsMod/Items.cs#L94

the line 27 core upgrade is set to make it a 350 core slot and sins its the same tire upgrade then it cant be use befor going to the next tire upgrade

**Comment by the-jomper** [comment]
allso the line 98 EngineUpgrade5 is set to 800 and the ShipCoreUpgrade5 is set to 500 at line 31

**Comment by Chriisuuuu** [comment]
I see, thank you very much.
All fixed!
