### ISSUE TITLE
Electric boogaloo mod gone

### ISSUE THREAD

**Issue by elrichzann** [christheboss894/Mods#4]
Why did you delete it? Where did it go? Can't even download it off the wayback machine, although I found it there.

**Comment by Chriisuuuu** [comment]
I deleted the mod as it hasn't worked with the game for 3 years, and people were complaining that it broke their game when they used it because of this.

**Comment by elrichzann** [comment]
I see! Thank you very much for the response. Crazy that people are dumb enough to blame you for a mod they can remove lol… but of course they are! Have a great day :)Sent from my iPhoneOn Nov 2, 2023, at 5:02 AM, Cheese ***@***.***> wrote:﻿
I deleted the mod as it hasn't worked with the game for 3 years, and people were complaining that it broke their game when they used it because of this.
